name: Test

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Package it
        run: | 
          npm ci
          npm package
      - name: Setup Minecraft
        id: minecraft
        uses: ReinIsNOTaDev/setup-minecraft@main
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: ${{ fromJson(steps.minecraft.outputs.package).javaVersion.majorVersion }}
      - name: Check Minecraft
        run: |
          echo Running Minecraft ${{ steps.minecraft.outputs.version }}.
          java -jar $MINECRAFT --help
